In [2]:
import pandas as pd
df = pd.read_csv("Hub_Express_Distribution.csv")
df.head()

,Customer ID,Category Product,Purchase Amount USD,Review Rating,Frequency of Purchase,Promo Code Active,Remise Appliquee,Previous Orders
0,1000,Cooking Oil,52000,NaN,Monthly,No,No,15
1,1001,Premium Beer,122000,NaN,Monthly,Yes,Yes,9
2,1002,Soap,51000,NaN,Weekly,Yes,Yes,0
3,1003,Soap,35000,NaN,Daily,No,No,4
4,1004,Cooking Oil,61000,NaN,Daily,Yes,Yes,4

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer ID            100 non-null    int64
 1   Category Product       100 non-null    str
 2   Purchase Amount USD    100 non-null    int64
 3   Review Rating          95 non-null     float64
 4   Frequency of Purchase  100 non-null    str
 5   Promo Code Active      100 non-null    str
 6   Remise Appliquee       100 non-null    str
 7   Previous Orders        100 non-null    int64
dtypes: float64(1), int64(3), str(4)
memory usage: 6.4 KB

In [4]:
df.describe()

       Customer ID  Purchase Amount USD  Review Rating  Previous Orders
count   100.000000           100.000000      95.000000       100.000000
mean   1049.500000         76170.000000       3.200000         9.520000
std      29.011492         45065.396925       1.388402         6.072758
min    1000.000000          6000.000000       1.000000         0.000000
25%    1024.750000         33750.000000       2.000000         4.000000
50%    1049.500000         76500.000000       3.000000         9.000000
75%    1074.250000        113000.000000       4.000000        15.000000
max    1099.000000        150000.000000       5.000000        20.000000

In [5]:
df.columns

Index(['Customer ID', 'Category Product', 'Purchase Amount USD',
       'Review Rating', 'Frequency of Purchase', 'Promo Code Active',
       'Remise Appliquee', 'Previous Orders'],
      dtype='str')

In [6]:
df.columns = df.columns.str.lower()

In [7]:
df.columns = df.columns.str.replace(" " , "_")

In [8]:
df.columns

Index(['customer_id', 'category_product', 'purchase_amount_usd',
       'review_rating', 'frequency_of_purchase', 'promo_code_active',
       'remise_appliquee', 'previous_orders'],
      dtype='str')

In [9]:
df [["promo_code_active","remise_appliquee"]].head()

  promo_code_active remise_appliquee
0                No               No
1               Yes              Yes
2               Yes              Yes
3                No               No
4               Yes              Yes

In [11]:
(df["promo_code_active"] == df["remise_appliquee"]).all()

np.True_

In [12]:
df = df.drop("promo_code_active", axis = 1)

In [13]:
df.columns

Index(['customer_id', 'category_product', 'purchase_amount_usd',
       'review_rating', 'frequency_of_purchase', 'remise_appliquee',
       'previous_orders'],
      dtype='str')

In [15]:
df.isnull().sum()

customer_id              0
category_product         0
purchase_amount_usd      0
review_rating            5
frequency_of_purchase    0
remise_appliquee         0
previous_orders          0
dtype: int64

In [18]:
df["review_rating"] = df.groupby("category_product")["review_rating"].transform(lambda x:x.fillna(x.median()))

In [19]:
df.isnull().sum()

customer_id              0
category_product         0
purchase_amount_usd      0
review_rating            0
frequency_of_purchase    0
remise_appliquee         0
previous_orders          0
dtype: int64

In [23]:
frequency_mapping = {"Daily":1, "Weekly":7, "Biweekly":14, "Monthly": 30}
df["frequency_purchase"] = df ["frequency_of_purchase"].map(frequency_mapping)
df[["frequency_purchase","frequency_of_purchase"]].head(10)

   frequency_purchase frequency_of_purchase
0                  30               Monthly
1                  30               Monthly
2                   7                Weekly
3                   1                 Daily
4                   1                 Daily
5                   7                Weekly
6                   1                 Daily
7                   7                Weekly
8                  14              Biweekly
9                  30               Monthly

In [53]:
from sqlalchemy import create_engine
username = "postgres"
password = "123"     
host = "localhost"
port = "5432"
database = "Hub_Express_Distribution_Behavior"
engine = create_engine( f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")
table_name = "express_distribution"
df.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into table '{table_name}' in database {database}.")

Data successfully loaded into table 'express_distribution' in database Hub_Express_Distribution_Behavior.